name: Bug Report
description: Report a bug or issue with TonX86
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Tell us what happened
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open file '...'
        2. Run/Debug '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true
  
  - type: textarea
    id: assembly
    attributes:
      label: Assembly Code (if applicable)
      description: The assembly code that triggers the bug
      render: asm
  
  - type: input
    id: version
    attributes:
      label: TonX86 Version
      description: What version of TonX86 are you using?
      placeholder: "0.0.1"
    validations:
      required: true
  
  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: What version of VS Code are you using?
      placeholder: "1.84.0"
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Debug Console Output
      description: Paste any relevant output from the Debug Console
      render: shell
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
